# Etapa de construção
FROM node:18-alpine AS builder

# Define o diretório de trabalho
WORKDIR /app

# Copia os arquivos de definição de dependências
COPY package*.json ./
COPY yarn.lock ./

# Instala as dependências
RUN yarn install --frozen-lockfile

# Copia o restante dos arquivos do projeto
COPY . .

# Expõe a porta 3000
EXPOSE 3000

# Comando para iniciar a aplicação em desenvolvimento
CMD ["yarn", "dev"]
